apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: myapp
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4200
